Description: RDS Resource 

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Description: Choose which VPC this ECS cluster should be deployed to
        Type: AWS::EC2::VPC::Id

    Subnets:
        Description: Choose which subnets this cluster should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    VPCSecurityGroups:
        Type: List<AWS::EC2::SecurityGroup::Id>

    DBName:
        Type: String

    DBInstanceIdentifier:
        Type: String

    Engine:
        Type: String

    MultiAZ:
        Type: String

    StorageEncrypted:
        Type: String

    KmsKeyId:
        Type: String

    MasterUsername:
        Type: String

    MasterUserPassword:
        Type: String

    DBInstanceClass:
        Type: String

    AllocatedStorage:
        Type: Number

Resources:
    DBSubnetGroup:
        Type: "AWS::RDS::DBSubnetGroup"
        Properties:
            DBSubnetGroupDescription: "RDS Subnet Group"
            SubnetIds: !Ref Subnets
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    DBInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBName: !Ref DBName
            DBInstanceIdentifier: !Ref DBInstanceIdentifier
            Engine: !Ref Engine
            MultiAZ: !Ref MultiAZ
            StorageEncrypted: !Ref StorageEncrypted
            KmsKeyId: !Ref KmsKeyId
            MasterUsername: !Ref MasterUsername
            DBInstanceClass: !Ref DBInstanceClass
            AllocatedStorage: !Ref AllocatedStorage
            MasterUserPassword: !Ref MasterUserPassword
            VPCSecurityGroups: !Ref VPCSecurityGroups
            DBSubnetGroupName:
                Ref: "DBSubnetGroup"
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

Outputs:
    DBInstance:
        Description: A reference to the created DBInstance
        Value: !Ref DBInstance

    DBEndpointAddress:
        Description: Endpoint for the instance
        Value: !GetAtt DBInstance.Endpoint.Address

    DBEndpointPort:
        Description: Port for the instance
        Value: !GetAtt DBInstance.Endpoint.Port
