Description: ECR Repository Resource

Parameters:
    RepositoryName:
        Type: String
    IAMUser:
        Type: String

Resources:
    ECRRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: !Ref RepositoryName
            RepositoryPolicyText:
                Version: "2012-10-17"
                Statement:
                    -
                        Sid: AllowPushPull
                        Effect: Allow
                        Principal:
                            AWS:
                                -   !Ref IAMUser
                        Action:
                            -   "ecr:GetDownloadUrlForLayer"
                            -   "ecr:BatchGetImage"
                            -   "ecr:BatchCheckLayerAvailability"
                            -   "ecr:PutImage"
                            -   "ecr:InitiateLayerUpload"
                            -   "ecr:UploadLayerPart"
                            -   "ecr:CompleteLayerUpload"

Outputs:
    URI:
        Value: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ "/", [ "amazonaws.com", !Ref ECRRepository ] ] ] ]
